config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: orviz-github-basic
        username_var: GIT_USER
        password_var: GIT_PASSWORD
      - id: incd_openstack
        variable: OPENSTACK_URL
      - id: incd-auth.dat
        type: file
        variable: JENKINS_AUTH_FILE

sqa_criteria:
  SvcQC.Dep:
    repos:
      im:
        container: imclient
        commands:
          - |
            #!/bin/bash
            printf "$(cat /im/test.radl)" "${OPENSTACK_URL}:${OPENSTACK_ID_PORT}" "${IM_IMAGE_ID}" > /im/test-ost.radl
            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/test-ost.radl > ./im_radl.json
            RETURN_CODE=$?
            echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
            echo "Infrastructure Manager output:"
            cat ./im_radl.json
            if [ ${RETURN_CODE} -eq 0 ]; then
              INFID=$(jq -r '[ .infid ] | .[]'  ./im_radl.json)
              echo "INFID=${INFID}"
              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
              echo "im_client.py destroy return code: $?"
            else
              exit ${RETURN_CODE}
            fi
          - |
            #!/bin/bash
            im_client.py -r "${IM_SERVER}" -a "${IM_AUTH_FILE}" create_wait_outputs /im/tosca_create.yml > ./im_tosca.json
            RETURN_CODE=$?
            echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
            echo "Infrastructure Manager output:"
            cat ./im_radl.json
            if [ ${RETURN_CODE} -eq 0 ]; then
              INFID=$(jq -r '[ .infid ] | .[]'  ./im_tosca.json)
              echo "INFID=${INFID}"
              im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
              echo "im_client.py destroy return code: $?"
            else
              exit ${RETURN_CODE}
            fi

environment:
  IM_IMAGE_ID: "5336f60b-d4cc-4285-a573-1b706cbbe40b"
  IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im/"
  OPENSTACK_ID_PORT: "5000"
  IM_AUTH_FILE: '/im/auth/auth.dat'
  JPL_DOCKERPUSH: "imclient"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: "45"
  #JPL_DEBUG: "true"

# Timeout after no activity in logs for this configuration (not the absolute duration)
#timeout: 1200
