version: "3.7"

services:
  imclient:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    image: "eoscsynergy/im-client:1.5.9"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./:/im
    entrypoint: [/bin/sleep, infinity]
