version: "3.7"

services:
  imclient:
    environment:
     - IM_AUTH_FILE='/im/auth/auth.dat'
     - IM_IMAGE_ID
     - IM_SERVER
    build:
      context: "."
      dockerfile: "./Dockerfile"
    image: "eoscsynergy/im-client:1.5.9"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./:/im
     - "${IM_AUTH_FILE}":/im/auth/auth.dat
    entrypoint: [/bin/sleep, infinity]
