version: "3.7"

services:
  imclient:
    environment:
     - IM_AUTH_FILE
     - IM_SERVER
     - OPENSTACK_URL
     - OPENSTACK_USER
     - OPENSTACK_PASS
     - IM_USER
     - IM_PASS
     - OPENSTACK_ID_PORT
    image: "grycap/im-client:ec3"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./:/im
     - ./auth/auth.dat:${IM_AUTH_FILE}
    entrypoint: [/bin/sleep, infinity]
