version: "3.7"

services:
  imclient:
    environment:
     - IM_AUTH_FILE
     - IM_IMAGE_ID
     - IM_SERVER
    build:
     - context: "."
     - dockerfile: "./Dockerfile"
    image: "eoscsynergy/im-client:1.5.9"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./:/im
     - ${JENKINS_AUTH_FILE}:${IM_AUTH_FILE}
    entrypoint: [/bin/sleep, infinity]
