version: "3.7"

services:
  imclient:
    environment:
     - IM_AUTH_FILE
     - RADL_IMAGE_ID
     - TOSCA_IMAGE_ID
     - IM_SERVER
     - OPENSTACK_URL
    image: "grycap/im-client:ec3"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./:/im
     - ${JENKINS_AUTH_FILE}:${IM_AUTH_FILE}
    entrypoint: [/bin/sleep, infinity]
